sudo: required

services:
  - docker

language: node_js
node_js:
  - "node"

# cache: yarn

after_success:
  - sh .travis/deploy_dockerhub.sh
  - test "$TRAVIS_BRANCH" = "master" && sh .travis/deploy_heroku.sh